---
title: "Conspiracies2Stats"
author: "Clare McDonald and Viveka Hall-Holt"
date: "1/18/2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r}
install.packages("ggpubr")
install.packages("gridExtra")
```


```{r, setup}
library(tidyverse)
library(mosaic)
library(psych)
library(ggpubr)
library(gridExtra)
covid_data <- read_csv("~/Stony Brook Research/COVID_19_December_2020_Cleaned_Data.csv")
covid_data <- subset(covid_data, duration_in_minutes > 10)
```

# Summary Statistics of Main Variables of Interest
```{r}
covid_data %>% 
  dplyr::select(Demographics_age, Demographics_gender, COVID_conspiracies_total, 
                STAIS_total, IUS_Total_Score, Green_PartA_short_score, Green_PartB_short_score, 
                Green_Total_Short_Score, MIS_total, PAS_total, neg_sxtypy_total) %>%
  describe()

# just formatted a little differently and I had to add the "dplyr::" b/c it wasn't working for me lol
# also IUS shows up as having 550 observations for me! 
```

# Correlations + Tests
```{r}
cor.test(covid_data$STAIS_total, covid_data$COVID_conspiracies_total)
cor.test(covid_data$IUS_Total_Score, covid_data$COVID_conspiracies_total)
cor.test(covid_data$Green_Total_Short_Score, covid_data$COVID_conspiracies_total)
cor.test(covid_data$MIS_total, covid_data$COVID_conspiracies_total)
cor.test(covid_data$PAS_total, covid_data$COVID_conspiracies_total)
cor.test(covid_data$neg_sxtypy_total, covid_data$COVID_conspiracies_total)
cor.test(covid_data$Demographics_societal, covid_data$COVID_conspiracies_total)
cor.test(covid_data$Demographics_economic, covid_data$COVID_conspiracies_total)
cor.test(covid_data$Rotters_general, covid_data$COVID_conspiracies_total)
cor.test(covid_data$Rotters_political, covid_data$COVID_conspiracies_total)
cor.test(covid_data$RLOC_Total_Score, covid_data$COVID_conspiracies_total)
```

# Scatterplots
```{r}
plot1 <- ggplot(covid_data, aes(x = Green_Total_Short_Score, y = COVID_conspiracies_total)) + 
         geom_point() +
         geom_smooth(method=lm, size=1.25, se=FALSE) +
         xlab ("GPTS") +
         ylab ("COVID-19 CT")
        # stat_cor(aes(label=..r.label..), label.x=70)

plot2 <- ggplot(covid_data, aes(x=MIS_total, y=COVID_conspiracies_total)) + 
         geom_point() +
         geom_smooth(method=lm, size=1.25, se=FALSE)+
         xlab ("MIS") +
         ylab ("COVID-19 CT")
        # stat_cor(aes(label=..r.label..), label.x=10)

plot3 <- ggplot(covid_data, aes(x=PAS_total, y=COVID_conspiracies_total)) + 
         geom_point() +
         geom_smooth(method=lm, size=1.25, se=FALSE)+
         xlab ("PAS")+
         ylab ("COVID-19 CT")
         #stat_cor(aes(label=..r.label..), label.x=12)

plot4 <- ggplot(covid_data, aes(x=PhAnS_score, y=COVID_conspiracies_total)) + 
         geom_point() +
         geom_smooth(method=lm, size=1.25, se=FALSE)+
         xlab ("PhAnS")+
         ylab ("COVID-19 CT")
         #stat_cor(aes(label=..r.label..), label.x=10)

plot5 <- ggplot(covid_data, aes(x=Social_Anhedonia_Score, y=COVID_conspiracies_total)) + 
         geom_point() +
         geom_smooth(method=lm, size=1.25, se=FALSE)+
         xlab ("SAS")+
         ylab ("COVID-19 CT")
         #stat_cor(aes(label=..r.label..), label.x=10)

plot6 <- ggplot(covid_data, aes(x=IUS_Total_Score, y=COVID_conspiracies_total)) + 
         geom_point() +
         geom_smooth(method=lm, size=1.25, se=FALSE) +
         #stat_cor(cor.coef.name = "r")+
         xlab ("IUS")+
         ylab ("COVID-19 CT")
         #stat_cor(aes(label=..r.label..), label.x=52)

plot7 <- ggplot(covid_data, aes(x=STAIT_total, y=COVID_conspiracies_total)) + 
         geom_point() +
         geom_smooth(method=lm, size=1.25, se=FALSE) +
         #stat_cor(cor.coef.name = "r")+
         xlab ("STAIT")+
         ylab ("COVID-19 CT")
        # stat_cor(aes(label=..r.label..))


plot8 <- ggplot(covid_data, aes(x=STAIS_total, y=COVID_conspiracies_total)) + 
         geom_point() +
         geom_smooth(method=lm, size=1.25, se=FALSE) +
         #stat_cor(cor.coef.name = "r")+
         xlab ("STAIS")+
         ylab ("COVID-19 CT")
        # stat_cor(aes(label=..r.label..), label.x=52)

grid.arrange(plot1, plot2, plot3, plot4, plot5, plot6, plot7, plot8, ncol=4)

ggplot(covid_data, aes(x = Demographics_societal, y = COVID_conspiracies_total)) + 
         geom_point() +
         geom_smooth(method=lm, size=1.25, se=FALSE) +
         xlab ("Societal") +
         ylab ("COVID-19 CT")
        # stat_cor(aes(label=..r.label..), label.x=70)

ggplot(covid_data, aes(x = Demographics_economic, y = COVID_conspiracies_total)) + 
         geom_point() +
         geom_smooth(method=lm, size=1.25, se=FALSE) +
         xlab ("Economic") +
         ylab ("COVID-19 CT")
        # stat_cor(aes(label=..r.label..), label.x=70)

ggplot(covid_data, aes(x = RLOC_Total_Score, y = COVID_conspiracies_total)) + 
         geom_point() +
         geom_smooth(method=lm, size=1.25, se=FALSE) +
         xlab ("Economic") +
         ylab ("COVID-19 CT")
        # stat_cor(aes(label=..r.label..), label.x=70)

ggplot(covid_data, aes(x = Rotters_general, y = COVID_conspiracies_total)) + 
         geom_point() +
         geom_smooth(method=lm, size=1.25, se=FALSE) +
         xlab ("Rotters_general") +
         ylab ("COVID-19 CT")
        # stat_cor(aes(label=..r.label..), label.x=70)

ggplot(covid_data, aes(x = Rotters_political, y = COVID_conspiracies_total)) + 
         geom_point() +
         geom_smooth(method=lm, size=1.25, se=FALSE) +
         xlab ("Economic") +
         ylab ("COVID-19 CT")
        # stat_cor(aes(label=..r.label..), label.x=70)
```

# Regressions
```{r}
covid_reg1 <- lm(COVID_conspiracies_total ~ MIS_total + PAS_total + PhAnS_score + Social_Anhedonia_Score + Green_Total_Short_Score, data = covid_data)
summary(covid_reg1)

covid_reg2 <- lm(COVID_conspiracies_total ~ Demographics_societal + Demographics_economic, data = covid_data)
summary(covid_reg2)

covid_reg3 <- lm(COVID_conspiracies_total ~ Demographics_societal + Demographics_economic + MIS_total + PAS_total + PhAnS_score + Social_Anhedonia_Score + Green_Total_Short_Score, data = covid_data)
summary(covid_reg3)

# Checking Missing for Covid Reg 1
summary(covid_data$MIS_total) # 67 NA
summary(covid_data$PAS_total) # 40 NA
summary(covid_data$PhAnS_score) # 45 NA
summary(covid_data$Social_Anhedonia_Score) # 45 NA
summary(covid_data$Green_Total_Short_Score) # 69 NA
summary(covid_data$COVID_conspiracies_total) # 57 NA

covid_data %>%
  dplyr::select(MIS_total, PAS_total, PhAnS_score, Social_Anhedonia_Score, Green_Total_Short_Score, COVID_conspiracies_total)
 
# Counted 240 rows that had at least 1 NA (prob some human error bc I did this by eye) so this lines up with obs deleted

# Testing Interactions b/w Demographics_societal and schizotypy variables
covid_reg_int1 <- lm(COVID_conspiracies_total ~ Demographics_societal + Demographics_economic + MIS_total + PAS_total + PhAnS_score + Social_Anhedonia_Score + Green_Total_Short_Score + Demographics_societal:MIS_total, data = covid_data)
summary(covid_reg_int1)

covid_reg_int2 <- lm(COVID_conspiracies_total ~ Demographics_societal + Demographics_economic + MIS_total + PAS_total + PhAnS_score + Social_Anhedonia_Score + Green_Total_Short_Score + Demographics_societal:PAS_total, data = covid_data)
summary(covid_reg_int2)

covid_reg_int3 <- lm(COVID_conspiracies_total ~ Demographics_societal + Demographics_economic + MIS_total + PAS_total + PhAnS_score + Social_Anhedonia_Score + Green_Total_Short_Score + Demographics_societal:PhAnS_score, data = covid_data)
summary(covid_reg_int3)

covid_reg_int4 <- lm(COVID_conspiracies_total ~ Demographics_societal + Demographics_economic + MIS_total + PAS_total + PhAnS_score + Social_Anhedonia_Score + Green_Total_Short_Score + Demographics_societal:Social_Anhedonia_Score, data = covid_data)
summary(covid_reg_int4)


# None are significant when accounting for other variables

# Attitude Variable
covid_data <- covid_data %>%
  mutate(Demographics_political_total = Demographics_societal + Demographics_economic)

hist(covid_data$`Attitudes/Behaviors_1`)

attitude_reg <- lm(COVID_conspiracies_total ~ `Attitudes/Behaviors_1` + Demographics_political_total, data = covid_data)
summary(attitude_reg)

cor.test(covid_data$Demographics_economic, covid_data$Demographics_societal)

green_reg <- lm(COVID_conspiracies_total ~ `Attitudes/Behaviors_1` + Green_Total_Short_Score + `Attitudes/Behaviors_1`:Green_Total_Short_Score, data = covid_data)
summary(green_reg)
```

