---
title: "R_script_for_quality_checks_of_cleaned_database"
author: "Clare McDonald & Viveka Hall-Holt"
date: "1/8/2021"
output: html_document
---

```{r setup, include = FALSE} 
library(tidyverse)
library(dplyr)
library(mosaic)
covid_data <- read_csv("~/Stony Brook Research/COVID_19_December_2020_Cleaned_Data.csv")
```

Example of format:
```{r}
##Name of item/score
# Frequency Distributions (mean/sd)

# Histogram 

# Verification of Variable Coding (Range)

# Scale Reliability

```

#Demographics
```{r}
##Demographics_age
# Frequency Distributions (mean/sd, n per scale)
covid_data$Demographics_age <- as.numeric(as.character(covid_data$Demographics_age))
favstats(~ Demographics_age, data = covid_data)#[c("mean","sd","n","missing")]
#length(covid_data$Demographics_age)-sum(is.na(covid_data$Demographics_age))

# Histogram 
hist(covid_data$Demographics_age)

#length(covid_data$Demographics_age)-sum(is.na(covid_data$Demographics_age)) 

# Verification of Variable Coding (Range)

# Scale Reliability
```

```{r}
##Demographics_gender
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Demographics_gender, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Demographics_gender)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##Demographics_ethnicity
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Demographics_ethnicity, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Demographics_ethnicity)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##Demographics_political_general
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Demographics_political_general, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Demographics_political_general)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##Demographics_societal
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Demographics_societal, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Demographics_societal)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##Demographics_economic
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Demographics_economic, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Demographics_economic)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##Demographics_economic
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Demographics_economic, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Demographics_economic)

# Verification of Variable Coding (Range)

# Scale Reliability

```

#Green Short Scores
```{r}
##Green_PartA_short_score
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_PartA_short_score, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_PartA_short_score)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##Green_PartB_short_score
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_PartB_short_score, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_PartB_short_score)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##Green_Total_Short_Score
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_Total_Short_Score, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_Total_Short_Score)

# Verification of Variable Coding (Range)

# Scale Reliability

```

#IUS Scores
```{r}
##IUS_Inhibitory_score
# Frequency Distributions (mean/sd, n per scale)
favstats(~ IUS_Inhibitory_score, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$IUS_Inhibitory_score)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##IUS_Prospective_score
# Frequency Distributions (mean/sd, n per scale)
favstats(~ IUS_Prospective_score, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$IUS_Prospective_score)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##IUS_Total_Score
# Frequency Distributions (mean/sd, n per scale)
favstats(~ IUS_Total_Score, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$IUS_Total_Score)

# Verification of Variable Coding (Range)

# Scale Reliability

```

# CRT?

# World Beliefs
```{r}
##World_Beliefs_1
# Frequency Distributions (mean/sd, n per scale)
favstats(~ World_Beliefs_1, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$World_Beliefs_1)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##World_Beliefs_2
# Frequency Distributions (mean/sd, n per scale)
favstats(~ World_Beliefs_2, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$World_Beliefs_2)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##World_Beliefs_3
# Frequency Distributions (mean/sd, n per scale)
favstats(~ World_Beliefs_2, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$World_Beliefs_3)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##World_Beliefs_4
# Frequency Distributions (mean/sd, n per scale)
favstats(~ World_Beliefs_4, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$World_Beliefs_4)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##World_Beliefs_5
# Frequency Distributions (mean/sd, n per scale)
favstats(~ World_Beliefs_5, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$World_Beliefs_5)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##World_Beliefs_6
# Frequency Distributions (mean/sd, n per scale)
favstats(~ World_Beliefs_6, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$World_Beliefs_6)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##World_Beliefs_7
# Frequency Distributions (mean/sd, n per scale)
favstats(~ World_Beliefs_7, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$World_Beliefs_7)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##World_Beliefs_8
# Frequency Distributions (mean/sd, n per scale)
favstats(~ World_Beliefs_8, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$World_Beliefs_8)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##World_Beliefs_9
# Frequency Distributions (mean/sd, n per scale)
favstats(~ World_Beliefs_9, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$World_Beliefs_9)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##World_Beliefs_10
# Frequency Distributions (mean/sd, n per scale)
favstats(~ World_Beliefs_10, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$World_Beliefs_10)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##World_Beliefs_11
# Frequency Distributions (mean/sd, n per scale)
favstats(~ World_Beliefs_11, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$World_Beliefs_11)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##World_Beliefs_12
# Frequency Distributions (mean/sd, n per scale)
favstats(~ World_Beliefs_12, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$World_Beliefs_12)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##World_Beliefs_13
# Frequency Distributions (mean/sd, n per scale)
favstats(~ World_Beliefs_13, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$World_Beliefs_13)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##World_Beliefs_14
# Frequency Distributions (mean/sd, n per scale)
favstats(~ World_Beliefs_14, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$World_Beliefs_14)

# Verification of Variable Coding (Range)

# Scale Reliability

```

```{r}
##World_Beliefs_15
# Frequency Distributions (mean/sd, n per scale)
favstats(~ World_Beliefs_15, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$World_Beliefs_15)

# Verification of Variable Coding (Range)

# Scale Reliability

```

# Green Short
```{r}
##Green_Short_A1
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_Short_A1, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_Short_A1)

# Verification of Variable Coding (Range)

```

```{r}
##Green_Short_A2
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_Short_A2, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_Short_A2)

# Verification of Variable Coding (Range)

```

```{r}
##Green_Short_A3
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_Short_A3, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_Short_A3)

# Verification of Variable Coding (Range)

```


```{r}
##Green_Short_A4
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_Short_A4, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_Short_A4)

# Verification of Variable Coding (Range)

```

```{r}
##Green_Short_A5
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_Short_A5, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_Short_A5)

# Verification of Variable Coding (Range)

```

```{r}
##Green_Short_A6
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_Short_A6, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_Short_A6)

# Verification of Variable Coding (Range)

```

```{r}
##Green_Short_A7
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_Short_A7, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_Short_A7)

# Verification of Variable Coding (Range)

```

```{r}
##Green_Short_A8
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_Short_A8, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_Short_A8)

# Verification of Variable Coding (Range)

```

```{r}
##Green_Short_B1
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_Short_B1, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_Short_B1)

# Verification of Variable Coding (Range)

```

```{r}
##Green_Short_B2
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_Short_B2, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_Short_B2)

# Verification of Variable Coding (Range)

```

```{r}
##Green_Short_B3
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_Short_B3, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_Short_B3)

# Verification of Variable Coding (Range)

```

```{r}
##Green_Short_B4
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_Short_B4, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_Short_B4)

# Verification of Variable Coding (Range)

```

```{r}
##Green_Short_B5
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_Short_B5, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_Short_B5)

# Verification of Variable Coding (Range)

```

```{r}
##Green_Short_B6
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_Short_B6, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_Short_B6)

# Verification of Variable Coding (Range)

```

```{r}
##Green_Short_B7
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_Short_B7, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_Short_B7)

# Verification of Variable Coding (Range)


```

```{r}
##Green_Short_B8
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_Short_B8, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_Short_B8)

# Verification of Variable Coding (Range)

```

```{r}
##Green_Short_B9
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_Short_B9, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_Short_B9)

# Verification of Variable Coding (Range)

```

```{r}
##Green_Short_B10
# Frequency Distributions (mean/sd, n per scale)
favstats(~ Green_Short_B10, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$Green_Short_B10)

# Verification of Variable Coding (Range)

```

# IUS Short
```{r}
##IUS_Short_1
# Frequency Distributions (mean/sd, n per scale)
favstats(~ IUS_Short_1, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$IUS_Short_1)

# Verification of Variable Coding (Range)

```

```{r}
##IUS_Short_2
# Frequency Distributions (mean/sd, n per scale)
favstats(~ IUS_Short_2, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$IUS_Short_2)

# Verification of Variable Coding (Range)

```

```{r}
##IUS_Short_3
# Frequency Distributions (mean/sd, n per scale)
favstats(~ IUS_Short_3, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$IUS_Short_3)

# Verification of Variable Coding (Range)


```

```{r}
##IUS_Short_4
# Frequency Distributions (mean/sd, n per scale)
favstats(~ IUS_Short_4, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$IUS_Short_4)

# Verification of Variable Coding (Range)


```

```{r}
##IUS_Short_5
# Frequency Distributions (mean/sd, n per scale)
favstats(~ IUS_Short_5, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$IUS_Short_5)

# Verification of Variable Coding (Range)


```

```{r}
##IUS_Short_6
# Frequency Distributions (mean/sd, n per scale)
favstats(~ IUS_Short_6, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$IUS_Short_6)

# Verification of Variable Coding (Range)


```

```{r}
##IUS_Short_7
# Frequency Distributions (mean/sd, n per scale)
favstats(~ IUS_Short_7, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$IUS_Short_7)

# Verification of Variable Coding (Range)


```

```{r}
##IUS_Short_8
# Frequency Distributions (mean/sd, n per scale)
favstats(~ IUS_Short_8, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$IUS_Short_8)

# Verification of Variable Coding (Range)


```

```{r}
##IUS_Short_9
# Frequency Distributions (mean/sd, n per scale)
favstats(~ IUS_Short_9, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$IUS_Short_9)

# Verification of Variable Coding (Range)


```

```{r}
##IUS_Short_10
# Frequency Distributions (mean/sd, n per scale)
favstats(~ IUS_Short_10, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$IUS_Short_10)

# Verification of Variable Coding (Range)


```

```{r}
##IUS_Short_11
# Frequency Distributions (mean/sd, n per scale)
favstats(~ IUS_Short_11, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$IUS_Short_11)

# Verification of Variable Coding (Range)

```

```{r}
##IUS_Short_12
# Frequency Distributions (mean/sd, n per scale)
favstats(~ IUS_Short_12, data = covid_data)#[c("mean","sd","n","missing")]

# Histogram 
hist(covid_data$IUS_Short_12)

# Verification of Variable Coding (Range)

```

# Counting NAs in each column
```{r, eval = FALSE}
# deleted column by column code to save space
colSums(is.na(covid_data))

#CRT not as consistent (294, 298, 295 x 4, 297; 4)
#World Beliefs consistent (72 x 5,  71 x 3, 72, 71 x 6; 1)
#Green Short consistent (71 x 8, 72, 71 x 3, 72, 71 x 2, 72 x 2, 71; 1)
#IUS consistent (359 x 12; 0)
#MIS consistent (96 x 8, 97, 96 x 5; 1)
#PAS consistent (69 x 15; 0)
#R_SAS consistent (86 x 15; 0)
#PhAnS consistent (72 x 2, 73, 72 x 9, 73, 72 x 2; 1)
#STAIT consistent (64 x 3, 65 x 9, 66, 65 x 2; 2)
#STAIS consistent (84 x 12, 86, 84 x 2, 85, 84 x 4; 2)
#PSWQ consistent (77 x 3, 78, 77 x 12)
#COVID_19_3 consistent (86 x 13, 87, 86 x 2; 1)
#Attitudes/Behaviors not totally consistent (66 x 8, 88, 66, 69 x 2; 22!)
#Health_Behavior consistent (except for questions 7-9 which were added later) (72 x 8 and 337 x 3; 0 and 0)
#Covid-19_1 consistent (88 x 3, 89, 88 x 9; 1)
#Covid_19_2 consistent (70 x 4, 71, 70 x 25; 1)
#PVDS consistent (81 x 15; 0)
#RLOC consistent (353 x 9, 355 x 2, 354 x 3, 355 x 2, 354, 353 x 3, 354 x 5, 353 x 4; 2)
#NFCS consistent (354 x 2, 353 x 4, 354, 353 x 8; 1)
```

```{r}
# histograms
ggplot(aes(x = Green_PartA_short_score), data = covid_data) +
  geom_histogram(fill = "blue", color = "black", bins = 15)
ggplot(aes(x = Green_PartB_short_score), data = covid_data) +
  geom_histogram(fill = "blue", color = "black", bins = 15)
ggplot(aes(x = Green_Total_Short_Score), data = covid_data) +
  geom_histogram(fill = "blue", color = "black", bins = 15)
ggplot(aes(x = IUS_Inhibitory_score), data = covid_data) +
  geom_histogram(fill = "blue", color = "black", bins = 15)
ggplot(aes(x = IUS_Prospective_score), data = covid_data) +
  geom_histogram(fill = "blue", color = "black", bins = 15)
ggplot(aes(x = IUS_Total_Score), data = covid_data) +
  geom_histogram(fill = "blue", color = "black", bins = 15)
ggplot(aes(x = GCBS_ci), data = covid_data) +
  geom_histogram(fill = "blue", color = "black", bins = 15)
ggplot(aes(x = GCBS_pw), data = covid_data) +
  geom_histogram(fill = "blue", color = "black", bins = 15)
ggplot(aes(x = GCBS_et), data = covid_data) +
  geom_histogram(fill = "blue", color = "black", bins = 15)
ggplot(aes(x = GCBS_mg), data = covid_data) +
  geom_histogram(fill = "blue", color = "black", bins = 15)
ggplot(aes(x = GCBS_gm), data = covid_data) +
  geom_histogram(fill = "blue", color = "black", bins = 15)
ggplot(aes(x = GCBS_total), data = covid_data) +
  geom_histogram(fill = "blue", color = "black", bins = 15)
```